### PR TITLE
Reworked some of the neural network notebooks

### PR DESCRIPTION
**Pull request by dhruvbalwada**

### CODE REVIEW

**Comment by IamShubhamGupto** [comment]
@dhruvbalwada I will get back on this pr in a couple of hours

**Comment by IamShubhamGupto** [comment]
@dhruvbalwada 
Jupyter book is currently setup to compile all notebooks within the `notebooks` folder. Since the `old_notebooks` is a sub folder, they compile too.

To address this issue, I updated the config file to ignore that subfolder in this PR - https://github.com/m2lines/L96_demo/pull/129

Once merged with this branch, we should be good to merge with the main branch as well

**Comment by dhruvbalwada** [comment]
Thanks Shubham. I merged your PR, will this PR break things if it was now merged (since it does not have your changes?)

**Review by IamShubhamGupto — APPROVED** [review]

**Comment by IamShubhamGupto** [comment]
> Thanks Shubham. I merged your PR, will this PR break things if it was now merged (since it does not have your changes?)

The PR was merged directly to this branch so we should be good to merge now

**Comment by NoraLoose** [comment]
Sorry for the late response! I see that the PR is merged already, so I guess a review is not required anymore?

**Comment by dhruvbalwada** [comment]
The way we have been doing this is to usually merge most of the changes to PR quickly, since it is quite hard to see all the changes in code version for the notebook. So (only if you have free time) it might still be good if you can look at the rendered notebooks and see if something seems off.

**Pull request merged**
