### PR TITLE
Rearrange chapters and update table of contents

### PR DESCRIPTION
**Pull request by dhruvbalwada**

### CODE REVIEW

**Comment by LaureZanna** [comment]
👍

**Comment by dhruvbalwada** [comment]
@LaureZanna could you approve this? This would mean :
- going to the tab that says "files changed"
- clicking the button "review changes"
- select "Approve" and submit.

**Review by LaureZanna — APPROVED** [review]

**Comment by LaureZanna** [comment]
@dhruvbalwada : I really like the new structure!!  I am wondering if we should think at the end how to modify some of the titles to make them a little more uniform.

**Comment by dhruvbalwada** [comment]
Yes, definitely will rename and beautify close to end. For now I mostly wanted to test if rearranging and naming works. Was trying to follow formatting similar to: https://physicsbaseddeeplearning.org/diffphys.html

**Pull request merged**
